modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="netjs"
version="${version}"
displayName="NetJS"
authors="KostromDan"
description='''
Addon for KubeJS for very limited safe network interaction.
'''

[[dependencies.netjs]]
modId="neoforge"
mandatory=true
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.netjs]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.netjs]]
modId="kubejs"
mandatory=false
versionRange="[2101.7.1,)"
ordering="NONE"
side="BOTH"
